version: '3.8'

services:
  elasticsearch:
    image: bitnami/elasticsearch:${ELASTIC_VERSION:-8.12.2}
    volumes:
      - elastic_data:/bitnami/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  kibana:
    image: bitnami/kibana:${KIBANA_VERSION:-8.12.2}
    volumes:
      - elastic_data:/bitnami/kibana
    ports:
      - 5601:5601
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch

volumes:
  elastic_data:
  kibana_data: